### ISSUE TITLE
Migrate Elasticsearch from Compose to elastic.co

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1125]
## Why
- We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.
- Elasticsearch version currently used is no longer maintained and Compose will no longer support it starting with October 31st

## What
- [x] Elasticsearch is upgraded to the latest version( gradually)
- [x] RC API and RC Index are updated(gradually) to use Elasticsearch latest version
- [x] Data from Compose is moved to elastic.co

**Comment by adinuca** [comment]
The migration will have 3 stages:
   - create beta environment( to be able to compare with production) #1136
1. Upgrade ES from version 2.4 to version 5
   - update rc-api to use ES library v5 #1129 
   - update rc-index to use ES library v5 #1134 
   - migrate the data from ES from version 2 to version 5
   - updadate nrgi-dcos with new config for ES
   - deploy to staging
   - test and ask Charles to test.

   - schedule best time to deploy in production
   - take rc-admin down(or show a maintenance page)
   - migrate data
   - change beta environment to use the new ES config
   - test in beta comparing with production
   - change config for production
   - deploy changes and test

2. Migrate data from Compose to Elastic(expected to take a few hours)
   - migrate the data from Compose to IO using elasticdump
   - updadate nrgi-dcos with new config for ES
   - deploy to staging
   - test and ask Charles to test.

   - schedule best time to deploy in production
   - take rc-admin down(or show a maintenance page)
   - migrate data
   - change beta environment to use the new ES config
   - test in beta comparing with production
   - change config for production
   - deploy changes and test

3. Upgrade ES from version 5 to version 6
   - update rc-api to use ES library v6 #1129 
   - update rc-index to use ES library v6 #1134 
   - migrate the data from ES from version 5 to version 6 by creating an ES5 deployment using the latest snapshot of the data and upgrading the new deployment to version 6
   - updadate nrgi-dcos with new config for ES
   - deploy to staging
   - test and ask Charles to test.

   - schedule best time to deploy in production
   - take rc-admin down(or show a maintenance page)
   - migrate data
   - change beta environment to use the new ES config
   - test in beta comparing with production
   - change config for production
   - deploy changes and test

**Comment by adinuca** [comment]
This has been done.
