### ISSUE TITLE
Migrate Elasticsearch deployment for RC Staging away from Compose

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1126]
## Why
- We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.
- Elasticsearch version currently used is no longer maintained and Compose will no longer support it starting with October 31st

## What
- [ ] RC Staging Elasticsearch deployment from Compose is migrated to the latest Elasticsearch version supported by Compose
- [ ] RC applications are updated to work with the new Elasticsearch version
- [ ] RC Staging Elasticsearch data is moved from Compose to elastic.co
- [ ] Testing is performed
- [ ] RC Staging deployment is removed from Compose

**Comment by charlesyoung** [comment]
@adinuca just checking on the timing of the migration so that I can be ready to do the testing.

**Comment by adinuca** [comment]
Hi @charlesyoung . I am expecting it to be ready for testing in the second week of October. I will let you know if the plan changes in any way.

Thank you!

**Comment by adinuca** [comment]
This is no longer needed as the migration will be made in 3 steps, as documented on #1125 .
