### ISSUE TITLE
Improve performance of RC

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1155]
## Why
RC platform has been intermittently down when crawled by bots between 9th of Nov and 16th of Nov. This has happened before but not as often.

## What
- [x] An investigation is done on why there are so many requests done by `rc-subsites` application to rc-api - for one page loaded for resourcecontracts.org there can be 20 calls to `rc-api`
   - [x] Issues are raised to address the high number of calls made to the API for each page, based on the investigation done.
- [ ] An investigation is done on why there are so many calls from `rc-api`to Elasticsearch  
   - [ ] Issues are raised to address the high number of calls made by `rc-api` to Elasticsearch based on the investigation done. 
- [ ] An investigation is done on how we could block some of the bots that are crawling the RC sites
   - [ ] Issues are raised to address findings from the investigation
- [ ] Elasticsearch is scaled back to the normal amount of resources( 4GB deployment)

**Comment by charlesyoung** [comment]
@adinuca should we still look at this?

**Comment by adinuca** [comment]
Hi @charlesyoung , yes this is still important.
