### ISSUE TITLE
Elasticsearch version reached EOL

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1301]
## Why
We received an email from Elastic cloud informing us that the version of ES that we are using has reached end of life and needs to be upgraded.

## What
- [x] Risks corresponding to the upgrade are identified (YI)
- [x] Code changes required for the upgrade are identified (YI)
- [x] Upgrade is scheduled
- [x] Code changes are tested against an upgraded ES deployment
- [x] Changes are moved to production

**Comment by charlesyoung** [comment]
Thanks @adinuca 

@anjesh what is the impact for RC and OLC?

**Comment by charlesyoung** [comment]
@anjesh can you please contact @candrei to get the ES Cloud details. 

Can you also review the code base to check the impact of the update.

**Comment by anjesh** [comment]
@candrei What would be the new version of ES in the ES cloud?

**Comment by candrei** [comment]
@anjesh ideally we'd want to upgrade to the most recent one v7.8 at the moment. We can also aim for 7.7 or 7.6 to get at least one year of support (see the `Maintenance tables` from https://www.elastic.co/support/eol).

**Comment by candrei** [comment]
@anjesh when do you estimate that you'll complete your research?

**Comment by candrei** [comment]
@anjesh do you have an update on your research?

**Comment by charlesyoung** [comment]
@anjesh do you have an update on your research?

**Comment by charlesyoung** [comment]
@anjesh @candrei what is the latest re this ticket?

**Comment by candrei** [comment]
@charlesyoung the upgrade is straightforward on our end, the biggest risk would be the possible incompatibilities of the application with the most recent version of Elasticsearch.

@anjesh could we support you in giving Elasticsearch 7.6+ a try? We could set up a clone version of the staging instance running the most recent version of Elasticsearch and give it a go with on staging for a couple of days if desired.

**Comment by charlesyoung** [comment]
@anjesh ??

**Comment by anjesh** [comment]
We haven't looked into this. Will be doing research this week and see what are the changes that needs to be done for the upgrade.

**Comment by charlesyoung** [comment]
@anjesh how much time will your research require?

**Comment by anjesh** [comment]
We are planning to spend around 6-8 hours on the research part. @man-git007 has already started and will have something to share by early next week.

**Comment by charlesyoung** [comment]
@anjesh we only have 5 hours left of savings. Can @candrei not help out?

**Comment by candrei** [comment]
@charlesyoung we can help if needed yet I think it would be inefficient to split the investigation between both teams. I would try to find a solution where YI can fully complete the research since they are the most knowledgeable of the code.

**Comment by anjesh** [comment]
@charlesyoung We has prepared the doc based on the research https://docs.google.com/document/d/1eGLFy7dfJ7K_3GHE5EfBrpCHlcSVhUnLar-qRD4e01c/edit. This upgrade is going to take some significant time and effort as we will need to upgrade php version as well to target latest ES.

**Comment by charlesyoung** [comment]
How much time will be required and what will happen if we don't upgrade ES? 

cc @candrei @SamCCSI

**Comment by iprunache** [comment]
@charlesyoung if we don't upgrade we're at risk of not being able to receive support from the cloud provider in case the Elasticsearch instance fails. The version we are running has reached End Of Life late last year and still runs without incident but the longer we keep it the bigger the chances we won't be able to revive it in case of failure.

Here it is in their words:
```
What happens if I do not upgrade my clusters?
You are at risk of not being able to receive support from Elastic. Upgrades to a compliant version helps ensure that Elastic Support is well equipped to be able to help you through any issues or questions that you may have.
```

The changes Anjesh has outlined are extensive but they buy us support for Elasticsearch until the end of 2021. And there should also be benefits from improved support and security for other components of the project too. PHP 5.6, which is in use now, has reached end of life in January 2019.

**Comment by charlesyoung** [comment]
Many thanks @iprunache 

How much time will it take to do the updates and can the work be split between YI and Vitamin or is that not feasible? 

cc @SamCCSI

**Comment by charlesyoung** [comment]
@anjesh @iprunache any update on the time required to do the updates? 


cc @SamCCSI

**Comment by anjesh** [comment]
As mentioned in the [doc](https://docs.google.com/document/d/1eGLFy7dfJ7K_3GHE5EfBrpCHlcSVhUnLar-qRD4e01c/edit), we think this is going to take 15-20 days of work.

**Comment by iprunache** [comment]
@charlesyoung Vitamin can do the infrastructure part as part of our ongoing maintenance and on a short time frame. I can't say for sure about doing part of the development work that Anjesh has outlined in the doc, Catalin will be best to answer this when he gets back on Monday.

What are your constraints in terms of budged and timeline? Might help us come up with the best solution.

**Comment by iprunache** [comment]
@anjesh @man-git007 We did a quick review of our production setup to see where we're at with the PHP versions running the 3 repos and here's what we found:
- `rc-api` and `rc-elasticsearch` already run on `PHP 7.1.22` in production. So it's possible to upgrade the ES client library to 7.x directly;
- `resourcecontracts.org` does run on `PHP 5.5.9` but I can't find any dependency on the ES client library for this project. As far as I know it uses `rc-api` and `rc-index` as interfaces to ES. Please correct me if I'm wrong.

Considering these findings it looks like the only upgrade needed is to take the ES library from 5.x to 7.x on `rc-api` and `rc-elasticsearch`.

If my assumptions are correct, how does this reflect in your estimates to do the upgrade on the codebase(Vitamin will handle the 2 step upgrade of the ES servers)?

**Comment by candrei** [comment]
Quick update here: preliminary tests showed that we can upgrade to Elasticsearch 6.8 without much headache. We'll attempt the migration of staging and see how it goes. This should buy us more time until we figure out how difficult would be to have support for Elasticsearch v7.

**Comment by iprunache** [comment]
I upgraded the staging Elasticsearch server to 6.8.12. The staging environment now fully runs on ES 6.8.12.

If no issues show up from this on staging by early next week, I'll also proceed to upgrade ES in the production environment.

**Comment by charlesyoung** [comment]
Thanks @iprunache and @candrei 

Should I be running tests on the Staging site?

**Comment by iprunache** [comment]
@charlesyoung some tests would be great!

What I did to test was to edit the metadata for some contract on staging admin and then confirm that the changes are visible on a subsite.

**Comment by charlesyoung** [comment]
OK, I will also publish new docs to test.

**Comment by charlesyoung** [comment]
@iprunache and @candrei I ran tests today and all looks good. 

How do we proceed moving this to the prod environment?

**Comment by candrei** [comment]
@charlesyoung thanks for the QA. I think we can go ahead and perform the upgrade to Elasticsearch 6.9 this week. @iprunache will reach out via email to coordinate on the best time window when the upgrade could take place.

**Comment by candrei** [comment]
@charlesyoung RC now makes use of Elasticsearch 6.8.12 which has an end of life 11/20/2020. I believe it's safe to operate with this version for another year, maybe 18months beyond November 2020.

**Comment by charlesyoung** [comment]
Great thanks. Can we close this ticket?

**Comment by candrei** [comment]
@charlesyoung yes, I was only looking for your email confirmation that RC admin is operating properly too. We're all set now! Closing.
